Register form check
LKV1812/js-forms pull request #3
Opened 2018-06-09 16:19 UTC by LKV1812

2018-06-09 22:47 UTC, nobleworkshop commented on js/register-form-check.js
> +				_inputLogin.before(_tooltipe);
Здесь в разметку добавляется сообщение об ошибке, но после не показывается. Его надо показать, например через fadeIn

2018-06-09 22:49 UTC, nobleworkshop requested changes
1) placeholder="Введите имя" поменять на email/ И атрибут name.
2) Тултип правильно пишется tooltip
3) После ввода email неверного формата ничего не происходит.
4) Если ввести email mail@mail.com то ошибка что email уже занят появляется следующим образом:
плавно показывается шапка, и резко все сообщение. Не критично, но можно все показывать плавно.

2018-06-13 11:53 UTC, LKV1812 reviewed
1. Ошибка о неверном формате email добавлена
2. tooltipe исправил на tooltip
3. В поле ввода email изменил атрибут name 
4. placeholder поменял значение на "введите email'
5. С необязательным замечанием так и не смог разобраться почему шапка сообщение появляется появляется плавно, а все сообщение жестко. Хотя вся разметка целиком записана в одну переменную

2018-06-15 20:56 UTC, nobleworkshop commented
@LKV1812  Хорошо.

4. Потому что у заголовка ошибки есть класс .error-hide {
    display: none;
} который ее скрывает по умолчанию. А у блока с текстом такого нет, и по умолчанию он отображается.

2018-06-15 20:57 UTC, nobleworkshop approved these changes
Looks Good!)

2018-06-16 12:28 UTC, merged